version: '3.1'

services:

  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 'admin12345678'
       MYSQL_DATABASE: 'curso'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'admin12345678'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
